name: CI

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Composer install
        uses: php-actions/composer@v6

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.2
          path: ""
          standard: phpcs.xml

      - name: PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.php

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Composer install
        uses: php-actions/composer@v6

      - name: PHPUnit
        uses: php-actions/phpunit@v3
        with:
          php_version: 8.2
          php_extensions: mbstring openssl
          test_suffix: "Test.php"
          configuration: phpunit.xml

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          flag-name: php-8.2-${{ matrix.env }}